name: CI Pipeline # name workflow

on:
  push:
    branches:
      - master

jobs:
  build: #job name
    runs-on: ubuntu-latest

    steps:
      - name: run script # stepname
        run: ls -la
        run: python hello.py #step
