name: task2.5 # name workflow

on:
  push:
    branches:
      - master

jobs:
  testTask2.5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run script_test
        run: python -m unittest mtest.py
